---
server:
  port: 9014
management:
  security:
    enabled: true
spring:
  rabbitmq:
    addresses: tcp://localhost:5672
    password: cloud
    username: spring
  cloud:
    stream:
      bindings:
        input:
          destination: task_topic
logging:
  level:
    org:
      springframework:
        cloud:
          task: DEBUG
          stream: DEBUG