---
server:
  port: 9013
management:
  security:
    enabled: true
spring:
  rabbitmq:
    addresses: tcp://localhost:5672
    host: localhost
    password: cloud
    port: 5672
    username: spring
  cloud:
    stream:
      bindings:
        output:
          destination: task_topic