---
server:
  port: 9003
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/MihaiBogdanEugen/config1
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - '*/perf'
              uri: https://github.com/MihaiBogdanEugen/config2
              search-paths:
                - 'station*'
management:
  security:
    enabled: true
security:
  basic:
    enabled: true
  user:
    name: config
    password: client