---
server:
  port: 1226
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MihaiBogdanEugen/config1
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - '*/perf'
              uri: https://github.com/MihaiBogdanEugen/config2
              search-paths:
                - 'station*'
management:
  security:
    enabled: true
security:
  basic:
    enabled: true
  user:
    name: bogdan
    password: mihai